/**
 * SpecTemplateEngine - Generates 18-section decision-complete specification
 * Each section is generated from wizard session data
 */

import { WizardSession } from '@prisma/client';

export class SpecTemplateEngine {
  async generate(session: WizardSession): Promise<string> {
    const sections: string[] = [];

    // Generate all 18 sections
    sections.push(this.generateSection1ExecutiveSummary(session));
    sections.push(this.generateSection2NonNegotiables(session));
    sections.push(this.generateSection3Scope(session));
    sections.push(this.generateSection4MVPRoadmap(session));
    sections.push(this.generateSection5Personas(session));
    sections.push(this.generateSection6UserFlows(session));
    sections.push(this.generateSection7FunctionalRequirements(session));
    sections.push(this.generateSection8NonFunctionalRequirements(session));
    sections.push(this.generateSection9SecurityPrivacy(session));
    sections.push(this.generateSection10Architecture(session));
    sections.push(this.generateSection11DataModel(session));
    sections.push(this.generateSection12APIContract(session));
    sections.push(this.generateSection13ErrorHandling(session));
    sections.push(this.generateSection14Analytics(session));
    sections.push(this.generateSection15AdminOps(session));
    sections.push(this.generateSection16Testing(session));
    sections.push(this.generateSection17DefinitionOfDone(session));
    sections.push(this.generateSection18DecisionLog(session));

    // Header
    const header = this.generateHeader(session);

    return header + '\n\n' + sections.join('\n\n---\n\n');
  }

  private generateHeader(session: WizardSession): string {
    return `# ${session.projectName || 'Unnamed Project'} - Decision-Complete Specification

**Generated:** ${new Date().toISOString()}
**Session ID:** ${session.id}
**Completeness Score:** ${session.completenessScore}%
**Status:** ${session.status}

> This document was generated by Autonomous Project Builder v0.8
> It contains all critical decisions and requirements needed for implementation.`;
  }

  // Section 1: Executive Summary
  private generateSection1ExecutiveSummary(session: WizardSession): string {
    const nonNeg = session.nonNegotiables ? JSON.parse(session.nonNegotiables) : {};
    const features = session.features ? JSON.parse(session.features) : [];
    const mvpFeatures = Array.isArray(features) ? features.filter((f: any) => f.scope === 'mvp') : [];

    return `## 1. Executive Summary

### Project Overview
**${session.projectName || 'Unnamed Project'}** is a ${session.projectType || 'software project'} with the following vision:

${session.description || 'No description provided.'}

### Key Objectives
- **Timeline:** ${session.timeline || 'Not specified'}
- **Team Size:** ${session.teamSize || 'Not specified'}
- **Budget Tier:** ${session.budgetTier || 'Not specified'}
- **MVP Features:** ${mvpFeatures.length} core features

### Critical Architectural Decisions
${this.formatNonNegotiablesForSummary(nonNeg)}

### Success Metrics
- Launch MVP within timeline with all core features
- Meet performance and security requirements
- Achieve ${session.completenessScore}% specification completeness
- Zero ambiguity - all decisions documented`;
  }

  private formatNonNegotiablesForSummary(nonNeg: any): string {
    const lines: string[] = [];
    if (nonNeg.e2ee === true) lines.push('- **End-to-End Encryption:** Required (affects all architecture decisions)');
    if (nonNeg.multiTenant === true) lines.push('- **Multi-Tenant Architecture:** Required (isolated data per customer)');
    if (nonNeg.offlineFirst === true) lines.push('- **Offline-First:** Required (local-first data sync)');
    if (nonNeg.multiRegion === true) lines.push('- **Multi-Region:** Required (data residency compliance)');
    if (lines.length === 0) return '- Standard web application architecture';
    return lines.join('\n');
  }

  // Section 2: Non-Negotiables & Assumptions
  private generateSection2NonNegotiables(session: WizardSession): string {
    const nonNeg = session.nonNegotiables ? JSON.parse(session.nonNegotiables) : {};

    return `## 2. Non-Negotiables & Assumptions

### 🔒 Non-Negotiable Decisions
These decisions are **locked** and cannot be changed without major architectural rework.

| Decision | Value | Impact |
|----------|-------|--------|
| End-to-End Encryption | ${this.formatBool(nonNeg.e2ee)} | ${nonNeg.e2ee ? 'Server cannot read content, complex key management' : 'Server-side processing enabled'} |
| Admin Can Read Data | ${this.formatBool(nonNeg.adminRead)} | ${nonNeg.adminRead ? 'Customer support possible, moderation enabled' : 'Blind database, privacy-focused'} |
| Phone Number Identity | ${this.formatBool(nonNeg.phoneIdentity)} | ${nonNeg.phoneIdentity ? 'SMS verification required, costs apply' : 'Email/username auth'} |
| Anonymous Users | ${this.formatBool(nonNeg.anonymousUsers)} | ${nonNeg.anonymousUsers ? 'No signup required, harder abuse prevention' : 'All users must register'} |
| Multi-Region Deployment | ${this.formatBool(nonNeg.multiRegion)} | ${nonNeg.multiRegion ? 'Data residency compliance, complex sync' : 'Single region, simpler ops'} |
| Offline-First Architecture | ${this.formatBool(nonNeg.offlineFirst)} | ${nonNeg.offlineFirst ? 'Works offline, CRDTs/sync engine needed' : 'Internet required'} |
| Multi-Tenant Architecture | ${this.formatBool(nonNeg.multiTenant)} | ${nonNeg.multiTenant ? 'Isolated customer data, tenant_id everywhere' : 'Single shared database'} |
| Open Source License | ${this.formatBool(nonNeg.openSource)} | ${nonNeg.openSource ? 'Public code, community contributions' : 'Proprietary code'} |

### 📋 Assumptions
- Team has expertise in chosen tech stack
- Budget covers infrastructure and third-party services
- Timeline is achievable with current team size
- Requirements are stable (no major scope changes mid-development)`;
  }

  private formatBool(value: boolean | undefined): string {
    if (value === true) return '✅ YES';
    if (value === false) return '❌ NO';
    return '⚠️ UNDECIDED';
  }

  // Section 3: In Scope / Out of Scope
  private generateSection3Scope(session: WizardSession): string {
    const inScope = session.inScope ? JSON.parse(session.inScope) : [];
    const outOfScope = session.outOfScope ? JSON.parse(session.outOfScope) : [];

    return `## 3. In Scope / Out of Scope

### ✅ In Scope
What this project **WILL** include:

${Array.isArray(inScope) && inScope.length > 0
  ? inScope.map((item: string, idx: number) => `${idx + 1}. ${item}`).join('\n')
  : '- No explicit in-scope items defined'}

### ❌ Out of Scope
What this project **WILL NOT** include (explicitly excluded):

${Array.isArray(outOfScope) && outOfScope.length > 0
  ? outOfScope.map((item: string, idx: number) => `${idx + 1}. ${item}`).join('\n')
  : '- No explicit out-of-scope items defined'}

### 🎯 Scope Management
- **Scope creep prevention:** All new feature requests must be evaluated against this list
- **Out-of-scope items** may become future roadmap items after MVP launch
- **Changes to scope** require stakeholder approval and timeline/budget adjustment`;
  }

  // Section 4: MVP vs Post-MVP Roadmap
  private generateSection4MVPRoadmap(session: WizardSession): string {
    const features = session.features ? JSON.parse(session.features) : [];
    const mvp = Array.isArray(features) ? features.filter((f: any) => f.scope === 'mvp') : [];
    const postMvp = Array.isArray(features) ? features.filter((f: any) => f.scope === 'post-mvp') : [];
    const nice = Array.isArray(features) ? features.filter((f: any) => f.scope === 'nice') : [];

    return `## 4. MVP vs Post-MVP Roadmap

### 🎯 MVP Features (${mvp.length})
**Must-have for initial launch:**

${mvp.length > 0
  ? mvp.map((f: any, idx: number) => `${idx + 1}. **${f.name}**${f.description ? `\n   - ${f.description}` : ''}`).join('\n')
  : '- No MVP features defined'}

### 📅 Post-MVP Features (${postMvp.length})
**Important but can wait for v2.0:**

${postMvp.length > 0
  ? postMvp.map((f: any, idx: number) => `${idx + 1}. **${f.name}**${f.description ? `\n   - ${f.description}` : ''}`).join('\n')
  : '- No post-MVP features defined'}

### ✨ Nice-to-Have Features (${nice.length})
**Would be great but not essential:**

${nice.length > 0
  ? nice.map((f: any, idx: number) => `${idx + 1}. **${f.name}**${f.description ? `\n   - ${f.description}` : ''}`).join('\n')
  : '- No nice-to-have features defined'}

### 📊 Roadmap Strategy
- **MVP:** Focus on core value proposition
- **Post-MVP:** Add advanced features based on user feedback
- **Nice-to-Have:** Evaluate ROI before implementation`;
  }

  // Section 5: Personas & Use Cases
  private generateSection5Personas(session: WizardSession): string {
    const personas = session.personas ? JSON.parse(session.personas) : [];

    return `## 5. Personas & Use Cases

${Array.isArray(personas) && personas.length > 0
  ? personas.map((p: any, idx: number) => `### Persona ${idx + 1}: ${p.name || 'Unnamed'}

**Role:** ${p.role || 'Not specified'}
**Technical Skill:** ${p.techSkill || 'Not specified'}
**Usage Frequency:** ${p.frequency || 'Not specified'}

**Goals:**
${p.goals && Array.isArray(p.goals)
  ? p.goals.filter((g: string) => g).map((g: string) => `- ${g}`).join('\n')
  : '- No goals defined'}
`).join('\n')
  : '### No Personas Defined\nConsider adding user personas to better understand user needs.'}`;
  }

  // Section 6: User Flows
  private generateSection6UserFlows(session: WizardSession): string {
    const flows = session.userFlows ? JSON.parse(session.userFlows) : [];

    return `## 6. User Flows

${Array.isArray(flows) && flows.length > 0
  ? flows.map((flow: any, idx: number) => `### Flow ${idx + 1}: ${flow.name || 'Unnamed Flow'}

${flow.steps && Array.isArray(flow.steps)
  ? flow.steps.map((step: any, stepIdx: number) => `**Step ${stepIdx + 1}:**
- **Actor:** ${step.actor}
- **Action:** ${step.action}
- **System Response:** ${step.system_response}`).join('\n\n')
  : 'No steps defined'}
`).join('\n')
  : '### No User Flows Defined\nUser flows are optional but help clarify requirements.'}`;
  }

  // Section 7: Functional Requirements
  private generateSection7FunctionalRequirements(session: WizardSession): string {
    const features = session.features ? JSON.parse(session.features) : [];

    return `## 7. Functional Requirements

### Core Functionality
${Array.isArray(features) && features.length > 0
  ? features.map((f: any, idx: number) => `**FR-${idx + 1}: ${f.name}**
- **Scope:** ${f.scope.toUpperCase()}
- **Priority:** ${f.priority}
${f.description ? `- **Description:** ${f.description}` : ''}
`).join('\n')
  : 'No functional requirements defined.'}

### Business Rules
- All MVP features must be implemented before launch
- Features must meet acceptance criteria before deployment
- User permissions and access control per feature`;
  }

  // Section 8: Non-Functional Requirements
  private generateSection8NonFunctionalRequirements(session: WizardSession): string {
    const perf = session.performanceReqs ? JSON.parse(session.performanceReqs) : {};
    const scale = session.scalabilityReqs ? JSON.parse(session.scalabilityReqs) : {};

    return `## 8. Non-Functional Requirements

### Performance
${perf.pageLoad ? `- **Page Load Time:** < ${perf.pageLoad} seconds` : '- Page load time: Not specified'}
${perf.apiResponse ? `- **API Response Time:** < ${perf.apiResponse} ms` : '- API response time: Not specified'}
- **Uptime:** 99.9% availability target

### Scalability
${scale.expectedUsers ? `- **Expected Concurrent Users:** ${scale.expectedUsers}` : '- Expected users: Not specified'}
${scale.peakLoad ? `- **Peak Load:** ${scale.peakLoad} requests/second` : '- Peak load: Not specified'}
${scale.dataVolume ? `- **Data Volume:** ${scale.dataVolume}` : '- Data volume: Not specified'}

### Accessibility
${session.accessibilityReq ? `- **WCAG Compliance:** Level ${session.accessibilityReq}` : '- WCAG compliance: Not specified'}
- Keyboard navigation support
- Screen reader compatibility

### Usability
- Intuitive interface requiring minimal training
- Mobile-responsive design
- Cross-browser compatibility (Chrome, Firefox, Safari, Edge)`;
  }

  // Section 9: Security & Privacy
  private generateSection9SecurityPrivacy(session: WizardSession): string {
    const sec = session.securityReqs ? JSON.parse(session.securityReqs) : {};
    const privacy = session.dataPrivacy ? JSON.parse(session.dataPrivacy) : {};
    const nonNeg = session.nonNegotiables ? JSON.parse(session.nonNegotiables) : {};

    return `## 9. Security & Privacy

### Authentication & Authorization
${sec.authMethod ? `- **Auth Method:** ${sec.authMethod}` : '- Auth method: Not specified'}
- Multi-factor authentication (recommended for sensitive data)
- Role-based access control (RBAC)
${nonNeg.anonymousUsers ? '- Anonymous user support enabled' : '- All users must authenticate'}

### Data Encryption
${nonNeg.e2ee ? '- **End-to-End Encryption:** Enabled (server cannot read content)' : ''}
${sec.encryption && Array.isArray(sec.encryption)
  ? sec.encryption.map((e: string) => `- ${e}`).join('\n')
  : '- Standard HTTPS/TLS encryption'}

### Compliance
${sec.compliance && Array.isArray(sec.compliance) && sec.compliance.length > 0
  ? sec.compliance.map((c: string) => `- **${c}:** Required`).join('\n')
  : '- No specific compliance requirements'}
${privacy.gdpr ? '- **GDPR:** EU data protection compliance' : ''}
${privacy.hipaa ? '- **HIPAA:** Healthcare data compliance' : ''}
${privacy.ccpa ? '- **CCPA:** California privacy compliance' : ''}

### Data Privacy
${privacy.retention ? `- **Data Retention:** ${privacy.retention}` : '- Data retention: Not specified'}
${privacy.backups ? '- **Backups:** Automated daily backups required' : ''}
${privacy.disasterRecovery ? '- **Disaster Recovery:** Plan required' : ''}
- User data deletion requests honored within 30 days
- Privacy policy and terms of service required`;
  }

  // Section 10: System Architecture
  private generateSection10Architecture(session: WizardSession): string {
    const tech = session.techStack ? JSON.parse(session.techStack) : {};
    const nonNeg = session.nonNegotiables ? JSON.parse(session.nonNegotiables) : {};

    return `## 10. System Architecture

### Tech Stack
${tech.backend ? `- **Backend:** ${tech.backend}` : '- **Backend:** Auto-recommend based on requirements'}
${tech.frontend ? `- **Frontend:** ${tech.frontend}` : '- **Frontend:** Auto-recommend based on requirements'}
${tech.database ? `- **Database:** ${tech.database}` : '- **Database:** Auto-recommend based on requirements'}
${tech.hosting ? `- **Hosting:** ${tech.hosting}` : '- **Hosting:** Auto-recommend based on requirements'}

### Architectural Patterns
${nonNeg.multiTenant ? '- **Multi-Tenant Architecture:** Isolated data per customer with tenant_id filtering' : '- **Single-Tenant Architecture:** Shared database for all users'}
${nonNeg.offlineFirst ? '- **Offline-First:** Local-first architecture with sync engine (CRDTs)' : '- **Online-First:** Standard client-server architecture'}
${nonNeg.multiRegion ? '- **Multi-Region:** Deployed across multiple geographic regions for data residency' : '- **Single-Region:** Centralized deployment'}

### High-Level Components
1. **Frontend Application:** User interface and client-side logic
2. **Backend API:** Business logic and data processing
3. **Database:** Persistent data storage
4. **Authentication Service:** User identity and access management
${nonNeg.e2ee ? '5. **Encryption Layer:** Client-side encryption/decryption' : ''}
${tech.hosting?.includes('CDN') || tech.hosting?.includes('Vercel') ? '6. **CDN:** Static asset delivery' : ''}

### Deployment Architecture
- **Environment Strategy:** Development → Staging → Production
- **CI/CD:** Automated testing and deployment pipeline
- **Monitoring:** Application performance monitoring (APM)
- **Logging:** Centralized logging for debugging and analytics`;
  }

  // Section 11: Data Model
  private generateSection11DataModel(session: WizardSession): string {
    const dataModel = session.dataModel ? JSON.parse(session.dataModel) : [];

    return `## 11. Data Model

### Database Schema

${Array.isArray(dataModel) && dataModel.length > 0
  ? dataModel.map((entity: any, idx: number) => `#### ${entity.entity || 'Entity' + idx}

**Fields:**
${entity.fields && Array.isArray(entity.fields)
  ? entity.fields.filter((f: string) => f).map((f: string) => `- ${f}`).join('\n')
  : '- No fields defined'}

${entity.relationships && Array.isArray(entity.relationships) && entity.relationships.length > 0
  ? `**Relationships:**
${entity.relationships.filter((r: string) => r).map((r: string) => `- ${r}`).join('\n')}`
  : ''}
`).join('\n')
  : '### No Data Model Defined\nDefine your database entities and relationships.'}

### Data Validation
- All required fields must be validated before saving
- Foreign key constraints enforced at database level
- Soft deletes recommended for user data (GDPR compliance)

### Data Migration Strategy
- Database migrations versioned and tracked
- Backward-compatible changes when possible
- Rollback plan for each migration`;
  }

  // Section 12: API Contract
  private generateSection12APIContract(session: WizardSession): string {
    const features = session.features ? JSON.parse(session.features) : [];
    const apis = session.externalAPIs ? JSON.parse(session.externalAPIs) : [];

    return `## 12. API Contract

### REST API Endpoints
${Array.isArray(features) && features.length > 0
  ? '**Core Endpoints (to be defined):**\n' + features.slice(0, 5).map((f: any) => `- \`/api/${f.name.toLowerCase().replace(/\s+/g, '-')}\` - ${f.name}`).join('\n')
  : 'API endpoints will be defined based on features.'}

### API Standards
- **Protocol:** RESTful HTTP/HTTPS
- **Format:** JSON request/response bodies
- **Versioning:** URL-based versioning (/api/v1/)
- **Authentication:** Bearer token in Authorization header
- **Rate Limiting:** 100 requests/minute per user (adjustable)

### Error Handling
- Standard HTTP status codes (200, 400, 401, 403, 404, 500)
- Structured error responses with error codes and messages
- Detailed error logging for debugging

### External API Integrations
${Array.isArray(apis) && apis.length > 0
  ? apis.map((api: any) => `- **${api.name}:** ${api.purpose} (${api.criticality})`).join('\n')
  : '- No external APIs defined'}`;
  }

  // Section 13: Error Handling & Edge Cases
  private generateSection13ErrorHandling(session: WizardSession): string {
    return `## 13. Error Handling & Edge Cases

### Error Handling Strategy
- **User-Facing Errors:** Clear, actionable error messages
- **System Errors:** Logged with stack traces for debugging
- **Network Errors:** Retry logic with exponential backoff
- **Validation Errors:** Field-level feedback with specific issues

### Common Edge Cases
1. **Network Failures:** Graceful degradation, offline indicators
2. **Concurrent Updates:** Optimistic locking or last-write-wins
3. **Invalid Input:** Comprehensive validation before processing
4. **Resource Limits:** Pagination, file size limits, rate limiting
5. **Authorization Failures:** Clear "access denied" messages

### Monitoring & Alerting
- **Error Tracking:** Sentry or similar for error monitoring
- **Uptime Monitoring:** Pingdom or UptimeRobot
- **Performance Monitoring:** New Relic or Datadog
- **Alert Thresholds:** Page on critical errors, email on warnings`;
  }

  // Section 14: Analytics & Telemetry
  private generateSection14Analytics(session: WizardSession): string {
    const privacy = session.dataPrivacy ? JSON.parse(session.dataPrivacy) : {};

    return `## 14. Analytics & Telemetry

### Product Analytics
- **User Behavior Tracking:** Page views, feature usage, user flows
- **Conversion Tracking:** Signup, activation, retention metrics
- **A/B Testing:** Capability for feature experiments
${privacy.gdpr || privacy.ccpa ? '- **Privacy-Compliant:** Cookie consent, data anonymization' : ''}

### Recommended Tools
- **Google Analytics** or **Mixpanel** for product analytics
- **Segment** for data pipeline management
- **Amplitude** for cohort analysis

### Technical Telemetry
- **Performance Metrics:** Page load times, API latency
- **Error Rates:** 4xx and 5xx response tracking
- **Resource Usage:** CPU, memory, database query performance
- **User Sessions:** Concurrent users, session duration

### Reporting
- **Weekly Dashboard:** Key metrics and trends
- **Monthly Review:** Growth, retention, feature adoption
- **Real-Time Alerts:** Critical errors, downtime, spikes`;
  }

  // Section 15: Admin & Operations
  private generateSection15AdminOps(session: WizardSession): string {
    const nonNeg = session.nonNegotiables ? JSON.parse(session.nonNegotiables) : {};

    return `## 15. Admin & Operations

### Admin Panel Requirements
${nonNeg.adminRead ? '- **User Data Access:** Admins can view user content for support' : '- **Limited Access:** Admins cannot view encrypted user content'}
- **User Management:** View, suspend, delete users
- **Content Moderation:** Review and moderate user-generated content
- **Analytics Dashboard:** Key business metrics
- **System Health:** Monitor performance and errors

### Operational Tasks
- **Database Backups:** Automated daily backups with 30-day retention
- **Security Updates:** Monthly dependency updates
- **Performance Optimization:** Quarterly performance audits
- **Cost Monitoring:** Track infrastructure spend

### Support Tools
- **Customer Support Portal:** Ticketing system integration
- **Logging & Debugging:** Access to application logs
- **Feature Flags:** Enable/disable features without deployment
${nonNeg.adminRead === false ? '- **Support Limitations:** Cannot access E2EE content' : ''}

### DevOps
- **Infrastructure as Code:** Terraform or similar
- **Container Orchestration:** Docker + Kubernetes (if needed)
- **Secret Management:** Environment variables, vault for API keys
- **Monitoring:** Prometheus + Grafana or cloud-native solutions`;
  }

  // Section 16: Testing Plan
  private generateSection16Testing(session: WizardSession): string {
    const features = session.features ? JSON.parse(session.features) : [];
    const mvpCount = Array.isArray(features) ? features.filter((f: any) => f.scope === 'mvp').length : 0;

    return `## 16. Testing Plan

### Testing Strategy
1. **Unit Tests:** 80%+ code coverage for business logic
2. **Integration Tests:** API endpoints and database operations
3. **End-to-End Tests:** Critical user flows (${mvpCount} MVP features)
4. **Performance Tests:** Load testing for expected traffic
5. **Security Tests:** OWASP Top 10 vulnerability scanning

### Test Coverage Requirements
- **Backend:** 80%+ unit test coverage
- **Frontend:** 60%+ component test coverage
- **Critical Paths:** 100% E2E test coverage for MVP features
- **Regression:** Automated tests for all bug fixes

### Testing Tools
- **Backend:** Jest, Mocha, or pytest
- **Frontend:** Jest, React Testing Library, Cypress
- **API:** Postman, REST Client
- **Load Testing:** Apache JMeter, k6

### QA Process
1. **Developer Testing:** Unit/integration tests before PR
2. **Code Review:** Peer review for all changes
3. **Staging Environment:** Full regression suite
4. **Production:** Smoke tests after deployment
5. **User Acceptance:** Beta testing with select users`;
  }

  // Section 17: Definition of Done
  private generateSection17DefinitionOfDone(session: WizardSession): string {
    return `## 17. Definition of Done

### Feature Completion Checklist
A feature is considered "done" when:

✅ **Implementation**
- [ ] Code implements all acceptance criteria
- [ ] Code follows project style guide and conventions
- [ ] No hardcoded secrets or credentials

✅ **Testing**
- [ ] Unit tests written and passing (80%+ coverage)
- [ ] Integration tests written and passing
- [ ] E2E tests for critical paths
- [ ] Manual QA testing completed

✅ **Documentation**
- [ ] API endpoints documented (if applicable)
- [ ] Code comments for complex logic
- [ ] README updated if needed
- [ ] User-facing documentation updated

✅ **Code Review**
- [ ] Pull request created with clear description
- [ ] Code reviewed by at least one peer
- [ ] All feedback addressed
- [ ] CI/CD pipeline passing (linting, tests, build)

✅ **Deployment**
- [ ] Deployed to staging environment
- [ ] Smoke tests passing in staging
- [ ] Product owner approval
- [ ] Deployed to production

✅ **Monitoring**
- [ ] Application logs reviewed for errors
- [ ] Performance metrics within acceptable range
- [ ] No unexpected errors in monitoring tools`;
  }

  // Section 18: Decision Log
  private generateSection18DecisionLog(session: WizardSession): string {
    const nonNeg = session.nonNegotiables ? JSON.parse(session.nonNegotiables) : {};
    const tech = session.techStack ? JSON.parse(session.techStack) : {};

    return `## 18. Decision Log

### Architecture Decision Records

#### ADR-001: Non-Negotiable Decisions
**Date:** ${session.createdAt.toISOString().split('T')[0]}
**Status:** Accepted
**Context:** Core architectural constraints defined in wizard
**Decision:**
${Object.entries(nonNeg).map(([key, value]) => `- ${key}: ${value ? 'YES' : 'NO'}`).join('\n')}

#### ADR-002: Tech Stack Selection
**Date:** ${session.updatedAt.toISOString().split('T')[0]}
**Status:** ${tech.backend && tech.frontend ? 'Accepted' : 'Proposed'}
**Context:** Technology choices for implementation
**Decision:**
${tech.backend ? `- Backend: ${tech.backend}` : '- Backend: To be decided'}
${tech.frontend ? `- Frontend: ${tech.frontend}` : '- Frontend: To be decided'}
${tech.database ? `- Database: ${tech.database}` : '- Database: To be decided'}
${tech.hosting ? `- Hosting: ${tech.hosting}` : '- Hosting: To be decided'}

#### ADR-003: Feature Prioritization
**Date:** ${session.updatedAt.toISOString().split('T')[0]}
**Status:** Accepted
**Context:** Scope and timeline constraints
**Decision:** Focus on MVP features for initial launch, post-MVP in v2.0

---

### Session Metadata
- **Session ID:** ${session.id}
- **Created:** ${session.createdAt.toISOString()}
- **Last Updated:** ${session.updatedAt.toISOString()}
- **Completeness:** ${session.completenessScore}%
- **Status:** ${session.status}

---

**End of Specification**
Generated by Autonomous Project Builder v0.8`;
  }
}
